---
openapi: 3.0.1
info:
  title: Address Weighting Service
  description: |-
    This relates to the address weighting API service. When a request is sent with details about a person, the API responds   with details of a matched person, if a match is found. If no matched person is found, the response will indicate as such.
    ```
    Change Log
    ```
    
      | Version | Date | Author | Description |
      |---|-----|------|-----|
      | 1.0.0 | 24-11-2022 | Mark Stead | Initial draft - created from EMS OAS file created by Ankur Mishra |
      | 1.0.1 | 20-12-2022 | Mark Stead | Removed version from server parameters and added scopes |
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: "1.0"
  x-integration-catalogue:
    reviewed-date: 2022-11-17T12:00:00Z
    platform: HIP
    publisher-reference: ems-address-weighting-service
    short-description: Address Weighting Service API
    status: ALPHA
    backends:
      - EMS
servers:
  - url: https://api.hip.prod.eis.ns2p.corp.hmrc.gov.uk/ems/
    description: Corporate - Production
  - url: https://api.hip.test.eis.ns2n.corp.hmrc.gov.uk/ems/
    description: Corporate - Test
  - url: https://hip.ws.hmrc.gov.uk/ems/
    description: MDTP - Production
  - url: https://hip.ws.ibt.hmrc.gov.uk/ems/
    description: MDTP - QA
security:
  - oAuth2:
      - read:address-weighting
tags:
  - name: person-plus-addresses-endpoint
    description: Person Plus Addresses Endpoint
paths:
  /v1/person-address-match:
    post:
      tags:
        - person-plus-addresses-endpoint
      description:
        Send a request containing details about a person. API response
        will contain details of a matching person (if found) along with match score
        and the single best identified address linked to that person
      operationId: doPersonLookupUsingPOST
      parameters:
        - name: CorrelationID
          in: header
          description: DES/IF Correlation ID - used for traceability purposes when present
          required: true
          schema:
            type: string
        - name: OriginatingSystem
          in: header
          description: The Originating System
          schema:
            type: string
      requestBody:
        description: the request parameters passed to match an entity
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonAddressMatchRequest"
            examples:
              PersonAddressMatchRequestExample:
                $ref: "#/components/examples/PersonAddressMatchRequestExample"
              PersonAddressMatchRequest2Example:
                $ref: "#/components/examples/PersonAddressMatchRequest2Example"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchPersonAddressResponseBody"
              examples:
                responseBodyExample:
                  $ref: "#/components/examples/ResponseExample"
                personNotFoundResponseBodyExample:
                  $ref: "#/components/examples/PersonNotFoundResponseExample"
        "201":
          description: Created
          content: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                  - origin
                  - response
                type: object
                properties:
                  origin:
                    $ref: "#/components/schemas/HIP-originEnum"
                  response:
                    oneOf:
                      - $ref: "#/components/schemas/HIP-failureResponse"
                      - $ref: "#/components/schemas/SimpleError400Object"
                additionalProperties: false
              examples:
                BadRequest:
                  $ref: "#/components/examples/SimpleError400ObjectExample"
        "401":
          description: Unauthorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "415":
          description: Unsupported media-type
          content: {}
        "422":
          description: Unprocessable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleError422Object"
              examples:
                Unprocessable:
                  $ref: "#/components/examples/SimpleError422ObjectExample"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                required:
                  - origin
                  - response
                type: object
                properties:
                  origin:
                    $ref: "#/components/schemas/HIP-originEnum"
                  response:
                    oneOf:
                      - $ref: "#/components/schemas/HIP-failureResponse"
                      - $ref: "#/components/schemas/SimpleError500Object"
                additionalProperties: false
              examples:
                InternalServerError:
                  $ref: "#/components/examples/SimpleError500ObjectExample"
      deprecated: false
      x-codegen-request-body-name: matchRequest
components:
  schemas:
    AddressMetadataMatchingDatasets:
      title: AddressMetadataMatchingDatasets
      type: object
      properties:
        effectiveDate:
          type: string
          example: yyyy-MM-dd
        name:
          type: string
    MatchPersonAddressResponseBody:
      title: MatchPersonAddressResponseBody
      type: object
      properties:
        addressSource:
          description:
            the source evidence dataset where the matched entity's details
            are found
          type: string
        matchedEntity:
          $ref: "#/components/schemas/MatchedPersonWithAddress"
        matchingOutcome:
          description:
            "the outcome of person matching, confirming whether a person\
                        \ matching the request parameters was found"
          enum:
            - IDENTIFIED_A_PERSON
            - FAILED_TO_IDENTIFY_THE_PERSON
            - FAILED_TO_IDENTIFY_A_SINGLE_BEST_MATCH_FOR_PERSON
          type: string
        requestNino:
          description: National Insurance Number of the person contained in the request
          type: string
        uuid:
          description: uuid of the response
          type: string
    MatchedPersonWithAddress:
      title: MatchedPersonWithAddress
      description: object contains person and address details
      type: object
      properties:
        address:
          $ref: "#/components/schemas/OneOfresponseBodyMatchedEntityAddressesItems"
        confidence:
          format: double
          description:
            "match score to indicate how good the match is, with a value\
                        \ between 0 and 1.  The higher the score, the better the match based on\
                        \ the parameters contained within the request."
          type: number
        dateOfBirth:
          $ref: "#/components/schemas/PartialDate"
        firstname:
          description: The first name or forename of the person
          type: string
        key:
          description: key or id of the entity matched
          type: string
        nino:
          description: The National Insurance Number of the person
          type: string
        surname:
          description: The surname of the person
          type: string
    OneOfresponseBodyMatchedEntityAddressesItems:
      title: OneOfresponseBodyMatchedEntityAddressesItems
      description: address details of the matched entity
      type: object
      properties:
        buildingName:
          description: name of the building
          type: string
        buildingNumber:
          description: building number
          type: string
        county:
          description: county
          type: string
        dependentThoroughfare:
          description: the thoroughfare
          type: string
        locality:
          description: the locality
          type: string
        postTown:
          description: the post town
          type: string
        postcode:
          description: the post code
          type: string
        subbuildingName:
          description: the sub building name
          type: string
        thoroughfare:
          description: the thorough fare
          type: string
        uprn:
          description:
            "Unique Property Reference Number (UPRN) of the address, as\
                        \ defined by Ordnance Survey"
          type: string
        latestDate:
          format: date
          description:
            the latest date when the matched entity details are found in
            an evidence dataset
          type: string
        matchingDatasets:
          description: the dataset(s) in which the entity details have been matched
          type: array
          items:
            $ref: "#/components/schemas/AddressMetadataMatchingDatasets"
        score:
          format: int32
          description: score for a matched entity based on the scorecard
          type: integer
    PartialDate:
      title: PartialDate
      required:
        - year
      type: object
      properties:
        day:
          type: string
        month:
          type: string
        year:
          type: string
    PersonAddressMatchRequest:
      title: PersonAddressMatchRequest
      required:
        - addressLine1
        - country
        - dateOfBirth
        - firstName
        - nino
        - surname
        - uuid
      type: object
      properties:
        addressLine1:
          description: Address Line 1 of the person's current or last known address
          maxLength: 35
          minLength: 1
          type: string
        addressLine2:
          description: Address Line 2 of the person's current or last known address
          maxLength: 35
          minLength: 0
          type: string
        addressLine3:
          description: Address Line 3 of the person's current or last known address
          maxLength: 35
          minLength: 0
          type: string
        addressLine4:
          description: Address Line 4 of the person's current or last known address
          maxLength: 35
          minLength: 0
          type: string
        addressLine5:
          description: Address Line 5 of the person's current or last known address
          maxLength: 35
          minLength: 0
          type: string
        country:
          description:
            "The country of the person's current or last known address\
                        \ address. This should be entered as <q>UNITED KINGDOM</q>, which includes\
                        \ England, Scotland, Wales and Northern Ireland but excludes the Isle\
                        \ of Man and Channel Islands. For international addresses (anything not\
                        \ within the United Kingdom) the description should conform to ISO-3166\
                        \ standard e.g. <q>AFGANISTAN</q>."
          maxLength: 99
          minLength: 1
          type: string
        dateOfBirth:
          format: date
          description:
            The date of birth of the person. Note that the date must not
            be before 1875 and the person must be 16 years or older
          type: string
        firstName:
          description: The first name or forename of the person
          maxLength: 99
          minLength: 1
          pattern: "^[-a-zA-Z ']{1,99}?$"
          type: string
        nino:
          description: The National Insurance Number of the person
          pattern: "^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?)$"
          type: string
        postcode:
          description:
            The postcode of the person's current or last known address.
            Postcode should only be populated when country is UNITED KINGDOM.
          pattern:
            "([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\\\
                        s?[0-9][A-Za-z]{2})"
          type: string
        secondName:
          description:
            The second or middle name(s) of the person. Should be separated
            by spaces where there are multiple
          maxLength: 99
          minLength: 0
          pattern: "^[-a-zA-Z ']{1,99}?$"
          type: string
        sex:
          description: The person's sex or gender
          enum:
            - Male
            - Female
            - Not Known
            - Not Specified
          type: string
        surname:
          description: The surname or family name of the person.
          maxLength: 99
          minLength: 1
          pattern: "^[-a-zA-Z ']{2,99}?$"
          type: string
        title:
          description: The title of the person
          enum:
            - Mr
            - Mrs
            - Miss
            - Ms
            - Dr
            - Rev
            - Sir
            - Lady
            - Lord
            - Dame
          type: string
        uuid:
          description: The universally unique identifier
          maxLength: 36
          minLength: 1
          type: string
    SimpleError400Object:
      title: SimpleErrorObject
      type: object
      properties:
        error:
          description: error
          type: string
        message:
          description: error message
          type: string
        timestamp:
          format: date-time
          description: timestamp
          type: string
    SimpleError422Object:
      title: SimpleErrorObject
      type: object
      properties:
        error:
          description: error
          type: string
        description:
          description: error description
          type: array
          items:
            type: object
    SimpleError500Object:
      title: SimpleErrorObject
      type: object
      properties:
        error:
          description: error
          type: string
        message:
          description: error message
          type: string
        timestamp:
          format: date-time
          description: timestamp
          type: string
    HIP-originEnum:
      enum:
        - HIP
        - HoD
      type: string
    HIP-failureResponse:
      required:
        - failures
      type: object
      properties:
        failures:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - type
              - reason
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
            additionalProperties: false
    HIP-originResponse:
      required:
        - origin
        - response
      type: object
      properties:
        origin:
          $ref: "#/components/schemas/HIP-originEnum"
        response:
          $ref: "#/components/schemas/HIP-failureResponse"
      additionalProperties: false
  examples:
    PersonAddressMatchRequestExample:
      value:
        firstName: GRAHAM
        surname: MACDONALD
        country: United Kingdom
        addressLine1: ADMIRALS WAY
        dateOfBirth: 1979-05-01
        uuid: 472ee977-0ca2-448b-ab13-d1e01060b71d
        nino: JB224466
    PersonAddressMatchRequest2Example:
      value:
        firstName: GRAHAM
        surname: MACDONALD
        title: Mr
        addressLine1: ADMIRALS WAY
        postcode: E14 9XQ
        country: United Kingdom
        dateOfBirth: 1979-05-01
        uuid: 472ee977-0ca2-448b-ab13-d1e01060b71d
        nino: JX826162
    ResponseExample:
      value:
        uuid: 472ee977-0ca2-448b-ab13-d1e01060b71d
        requestNino: JX826162
        matchingOutcome: IDENTIFIED_A_PERSON
        addressSource: Enterprise Matching
        matchedEntity:
          nino: ""
          firstname: GRAHAM
          surname: MACDONALD
          key: P5641494192F
          dateOfBirth:
            year: "1979"
            month: "05"
            day: ""
          confidence: 0.75
          address:
            matchingDatasets:
              - name: COMPANIES_HOUSE_PSC
                effectiveDate: 2021-06-05
            uprn: "6063671"
            subbuildingName: SUITE 9
            buildingName: ENSIGN HOUSE
            buildingNumber: "17"
            dependentThoroughfare: ""
            thoroughfare: ADMIRALS WAY
            locality: CANARY WHARF
            postTown: LONDON
            county: TOWER HAMLETS
            postcode: E14 9XQ
            latestDate: 2021-06-05
            score: 11
    PersonNotFoundResponseExample:
      value:
        uuid: 472ee977-0ca2-448b-ab13-d1e01060b71d
        requestNino: JX826162
        matchingOutcome: FAILED_TO_IDENTIFY_THE_PERSON
        addressSource: Enterprise Matching
    SimpleError400ObjectExample:
      value:
        error:
          "Exception thrown: org.springframework.web.bind.MissingRequestHeaderException:\
                    \ Missing request header CorrelationID for method parameter of type String"
        message:
          Missing request header 'CorrelationID' for method parameter of type
          String
        timestamp: 2022-11-04T17:38:07.456276
    SimpleError422ObjectExample:
      value:
        error: Unprocessable
        description:
          - dateOfBirth: invalid format
    SimpleError500ObjectExample:
      value:
        error:
          "Exception thrown: reactor.core.Exceptions$ReactiveException: javax.net.ssl.SSLHandshakeException:\
                    \ PKIX path validation failed: java.security.cert.CertPathValidatorException:\
                    \ validity check failed"
        message:
          "javax.net.ssl.SSLHandshakeException: PKIX path validation failed:\
                    \ java.security.cert.CertPathValidatorException: validity check failed"
        timestamp: 2022-11-04T17:38:07.456276
  securitySchemes:
    oAuth2:
      type: oauth2
      description: Keycloak OAuth2 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: /realms/hip/protocol/openid-connect/token
          scopes:
            read:address-weighting:
              Return the best matching address and weighted
              score for an individual
