---
openapi: 3.0.3
info:
  title: NPS Interface Catalogue for the Find My Nino Service
  description: |-
    # Usage Terms
    These interfaces are business-critical interfaces for HMRC, supporting thousands of staff - all consumption, or change in consumption levels, should be registered and fully approved (see Registered Consumers below).
  contact:
    name: HMRC NPS Live Service
    url: http://
    email: user@hmrc.gov.uk
  license:
    name: HMRC
    url: https://license.example.hmrc.gov.uk
  version: 1.0.1
  x-integration-catalogue:
    reviewed-date: 2023-11-15T14:13:39.795149899Z
    publisher-reference: nps-find-my-nino
    short-description: "Trigger issuing of National Insurance Number Letter from NINO,\
      \ Name and Address"
    status: BETA
    api-type: SIMPLE
    platform: HIP
    backends:
    - NPS
servers:
- url: https://api.hip.prod.eis.ns2p.corp.hmrc.gov.uk/nps/
  description: Corporate - Production
- url: https://api.hip.test.eis.ns2n.corp.hmrc.gov.uk/nps/
  description: Corporate - Test
- url: https://hip.ws.hmrc.gov.uk/nps/
  description: MDTP - Production
- url: https://hip.ws.ibt.hmrc.gov.uk/nps/
  description: MDTP - QA
security:
- oAuth2:
  - read:nps-get-nino
paths:
  /nps-json-service/nps/itmp/find-my-nino/api/v1/individual/{identifier}:
    post:
      tags: []
      summary: NPS Interface Specification to FMN service to NPS (#0391).
      description: |-
        # Purpose
        This API trigger the existing Business As Usual (BAU) process in National Insurance (NI) and Pay  As You Earn (PAYE) System (NPS) that issue a National Insurance Number (NINO) confirmation letter to enable Authorityâ€™s customers to fully interact digitally without the need to call the Authority when they require a NINO letter.

        # Volumes & Registered Consumers
        This API is consumed by the following 'Registered Consumers' who would all need to be impacted when a new consumer with an associated new load first registers to use the service, or an uplift is required to the API. Each 'Registered Consumer' below will receive an additional Security Spec. document that outlines how to connect to the various environments as well as any consumer-specific authorisation/authentication details - this is unique to their connection.

        | Consumer | Average API Calls Per Hour | Peak API Calls Per Hour | Peak TPS |
        |----------|------------------------|---------------------|----------|
        | MDTP FMN Service | xxx | xxx | xxx |

        *TPS = Transactions per second

        ## Version Log
        | Version | Date | Author | Description |
        |---------|------|--------|-------------|
        | 1.0.0 | 03/07/2023 | Rajnish Katiyar, Majd Moghrabi| Inital Draft |
        | 1.0.1 | 13/11/2023 | Majd Moghrabi| Removed 409 error responses as unreachable by the API. 405 and 415 error responses excluded as they are framework related errors |
      operationId: findMyNino
      parameters:
      - $ref: '#/components/parameters/CorrelationId'
      - $ref: '#/components/parameters/Identifier'
      - $ref: '#/components/parameters/GovUkOriginatorId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FindMyNinoRequest'
            examples:
              maximallyPopulatedRequest:
                summary: With all request properties
                value:
                  firstForename: Jean-Pierre
                  surname: van Cholmondley-warner
                  dateOfBirth: 2022-06-27
                  postCode: X9 9XX
        required: true
      responses:
        "202":
          description: Successful - Accepted
        "400":
          description: Bad Request
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/errorResponse'
                additionalProperties: false
              examples:
                DLO/RLS/NFA address:
                  value:
                    origin: HoD
                    response:
                      jsonServiceError:
                        requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                        message: BAD_REQUEST
                        appStatusMessageCount: 1
                        appStatusMessageList:
                          appStatusMessage:
                          - "63472"
                "3 letters in rolling 12 months":
                  value:
                    origin: HoD
                    response:
                      jsonServiceError:
                        requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                        message: BAD_REQUEST
                        appStatusMessageCount: 1
                        appStatusMessageList:
                          appStatusMessage:
                          - "63471"
                Non-matching postcode:
                  value:
                    origin: HoD
                    response:
                      jsonServiceError:
                        requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                        message: BAD_REQUEST
                        appStatusMessageCount: 1
                        appStatusMessageList:
                          appStatusMessage:
                          - "63473"
        "401":
          description: Unauthorized
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Invalid Credentials:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: INVALID_CREDENTIALS
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - Invalid Credentials supplied
        "404":
          description: Not Found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Matching Resource Not Found:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: MATCHING_RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - Uri does not exist
                Resource not found:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - "65370"
                Account status invalid:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - "63467"
                Account deceased:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - "63468"
                CRN indicator invalid:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - "63469"
                Account not matched:
                  value:
                    jsonServiceError:
                      requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                      message: RESOURCE_NOT_FOUND
                      appStatusMessageCount: 1
                      appStatusMessageList:
                        appStatusMessage:
                        - "63470"
        "500":
          description: Generic Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/errorResponse'
                additionalProperties: false
              examples:
                Generic Server Error:
                  value:
                    origin: HoD
                    response:
                      jsonServiceError:
                        requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                        message: GENERIC_SERVER_ERROR
                        appStatusMessageCount: 1
                        appStatusMessageList:
                          appStatusMessage:
                          - Internal Server Error
        "501":
          description: Not Implemented
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/errorResponse'
                additionalProperties: false
              examples:
                Not Implemented:
                  value:
                    origin: HoD
                    response:
                      jsonServiceError:
                        requestURL: /itmp/find-my-nino/api/v1/individual/AA123456
                        message: NOT_IMPLEMENTED
                        appStatusMessageCount: 1
                        appStatusMessageList:
                          appStatusMessage:
                          - Context determined but code is not active
components:
  schemas:
    nationalInsuranceNumber:
      description: National Insurance Number - unique for an individual - note not
        all individuals qualify to be issued with one.
      maxLength: 8
      minLength: 8
      pattern: "^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}$"
      type: string
      example: AA123456
    firstForename:
      description: The first name or forename of the individual.
      maxLength: 99
      minLength: 1
      pattern: "^([A-Za-z '-])+$"
      type: string
      example: Jean-Pierre
    surname:
      description: The surname of the individual.
      maxLength: 99
      minLength: 2
      pattern: "^([A-Za-z '-])+$"
      type: string
      example: van Cholmondley-warner
    dateOfBirth:
      format: date
      description: The date of birth of the individual.
      type: string
      example: 2020-03-10
    postCode:
      description: "The postal code for an address. Includes formats of: X9 9XX, X99\
        \ 9XX, XX9 9XX, XX99 9XX, X9X 9XX, XX9X 9XX, BFPO 999."
      maxLength: 9
      minLength: 6
      pattern: "^(([A-Z]{1,2}[0-9][0-9A-Z]? [0-9][A-Z]{2})|(BFPO ?[0-9]{1,3}))$"
      type: string
      example: XX9X 9XX
    correlationId:
      format: uuid
      description: Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      type: string
      example: e470d658-99f7-4292-a4a1-ed12c72f1337
    govUkOriginatorId:
      description: Unique identifier to determine which service an API call originated
        from.
      type: string
      example: DA2_FMN
    errorResponse:
      title: Error Response
      description: Error Response Payload for this API.
      type: object
      properties:
        jsonServiceError:
          description: Displays the reason that a failure has occurred.
          required:
          - appStatusMessageCount
          - appStatusMessageList
          - message
          - requestURL
          type: object
          properties:
            requestURL:
              description: Request URL String.
              type: string
            message:
              description: Technical error message.
              type: string
            appStatusMessageCount:
              description: Count of appStatusMessageList entries.
              type: integer
            appStatusMessageList:
              required:
              - appStatusMessage
              type: object
              properties:
                appStatusMessage:
                  description: The message string denoting why a failure occurred.
                  type: array
                  items:
                    type: string
              additionalProperties: false
          additionalProperties: false
      additionalProperties: false
    FindMyNinoRequest:
      description: Empty Request payload for this API.
      required:
      - dateOfBirth
      - firstForename
      - postCode
      - surname
      type: object
      properties:
        firstForename:
          $ref: '#/components/schemas/firstForename'
        surname:
          $ref: '#/components/schemas/surname'
        dateOfBirth:
          $ref: '#/components/schemas/dateOfBirth'
        postCode:
          $ref: '#/components/schemas/postCode'
      additionalProperties: false
    HIP-originEnum:
      enum:
      - HIP
      - HoD
      type: string
    HIP-failureResponse:
      required:
      - failures
      type: object
      properties:
        failures:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - type
            - reason
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
            additionalProperties: false
    HIP-originResponse:
      required:
      - origin
      - response
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/HIP-originEnum'
        response:
          $ref: '#/components/schemas/HIP-failureResponse'
      additionalProperties: false
  parameters:
    CorrelationId:
      name: correlationId
      in: header
      description: Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      required: true
      schema:
        $ref: '#/components/schemas/correlationId'
      style: simple
      explode: false
    GovUkOriginatorId:
      name: gov-uk-originator-id
      in: header
      description: Unique identifier to determine which service an API call originated
        from.
      required: true
      schema:
        $ref: '#/components/schemas/govUkOriginatorId'
      style: simple
      explode: false
    Identifier:
      name: identifier
      in: path
      description: National Insurance Number - unique for an individual - note not
        all individuals qualify to be issued with one.
      required: true
      schema:
        $ref: '#/components/schemas/nationalInsuranceNumber'
      style: simple
      explode: false
  headers:
    CorrelationId:
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/correlationId'
    GovUkOriginatorId:
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/govUkOriginatorId'
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth2 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: /tokenUrl/not-required
          scopes:
            read:nps-get-nino: Issue a National Insurance Number (NINO) confirmation
              letter